### ISSUE TITLE
Improve package name

### ISSUE THREAD

**Issue by jcfr** [DigitalSlideArchive/histomics_stream#20]
Few suggestions:
* rename it to have a more specific name describing the fact it is used for Whole-slide images. For example `tensorflow-wholeslide-image-reader`
* make sure that while the package submitted to pypi include a `-` instead of a `_` (this is by convention - see https://pypi.org/search/?q=tensorflow)

**Comment by Leengit** [comment]
It is renamed to `histomics_stream` with Pull Request #28.  We use underscores throughout rather than hyphens.
