### ISSUE TITLE
Google Colab badge for example notebook

### ISSUE THREAD

**Issue by thewtex** [DigitalSlideArchive/histomics_stream#42]

**Comment by thewtex** [comment]
-- Will require `pip install` of dependencies at the start of the notebook.
-- We should have a remotely hosted dataset where we do not have to download the full dataset before starting.
-- We should demonstrate application of a useful histopathology model.

**Comment by Leengit** [comment]
The item from this Issue #42 that was not implemented by Pull Request #43 has been created as Issue #44.
