### ISSUE TITLE
Use large_image wheel for dependency build

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/histomics_stream#45]
large_image has a wheel to simplify the installation of the many tile sources.

histomics-stream should use the large_image wheel during it's build.

**Comment by Leengit** [comment]
We want to have the equivalent of
```bash
python -m pip install -U 'large_image[all]' --find-links https://girder.github.io/large_image_wheels
```
in `setup.py` and for PyPI (`pyproject.toml`).

**Comment by Leengit** [comment]
Apparently PyPI specifically disallows getting dependent packages from anywhere other than PyPI itself.  @manthey: any thoughts on how to get `large_image` (as a dependency for PyPI's `histomics_stream`) with as much quality as is available from  https://girder.github.io/large_image_wheels?

**Comment by manthey** [comment]
I don't know how to do this.  You can add the `--find-links` in a requirements.txt file that is consumed by `pip -r`, or in a tox specification, but I don't think you can do it in a `pyproject.toml` file or `setup.py`.

I think we'd have to emit packages with wheels to pypi, but then they would have different names, which would prevent easy working with alternate environments (and, as far as I know, you can't have an extras_require that _removes_ dependencies, so you can't default to an alternate named package but have it easily overridable).

**Comment by Leengit** [comment]
We will change installation instructions to be
```bash
pip install -U 'large_image[all]' --find-links https://girder.github.io/large_image_wheels
pip install histomics_stream
```
