### ISSUE TITLE
Resize generated tiles

### ISSUE THREAD

**Issue by cooperlab** [DigitalSlideArchive/histomics_stream#53]
When the desired magnification is not available, we read from a higher magnification and set 'factor' < 1.

Resizing as part of the tile streaming pipeline would benefit users. Anti-aliasing should be applied since factor < 1 always. This likely needs to be performed on the CPU, as the GPU kernels for anti-aliasing are not available. The easiest and best way may be to use large_image. TileSource.getRegion defaults to Lanczos (which uses PIL). We can provide a binary flag "resize" that defaults to true when building a study. 

In the example notebook we can show the alternative approach with resize=False and resizing the tiles after they are popped.

**Comment by Leengit** [comment]
Excellent plan.  We may wish to rename `resize` because it could be a little confusing.  If "size" is interpreted in terms of the number of pixels then there is (1) a requested size, (2) a natively available size, and (3) the size put into the tensorflow Dataset.  By `resize==True` we mean that the second and third don't have to be the same number of pixels, but others might think that we mean that the first and third don't have to be the same number of pixels -- which is the opposite of our meaning.

**Comment by Leengit** [comment]
I propose: Currently the constructor for the `histomics_stream.FindResolutionForSlide` class takes three arguments, `study`, `desired_magnification`, `magnification_tolerance`.  Currently that third argument is a value like `0.02` which tells histomics_stream to choose the nearest native magnification among those that are at least 98% of the requested magnification.  I propose that we change the `magnification_tolerance` argument to instead take one of these values:

1. `"objective"`: histomics_stream will use the highest native magnification available.
2. `"native"`: histomics_stream will use the lowest native resolution available among those that are at least 98% of the requested magnification.  
3. `"exact"`: histomics_stream will use the `"native"` resolution but will resample the pixels to be the requested magnification.  `factor` will be `1.0` in this case.

In all cases, `factor` will be set to the ratio of the requested magnification to magnification that is used.

**Comment by cooperlab** [comment]
Maybe replace "objective" with "scan" or "scanning". Some people refer to a 5X derived from a 20X scan as "5X objective".

For "exact" users need to be able to determine that the magnification of returned tile is not present in the WSI, and that it has been resized. Capturing this mode in the dict would suffice. Related to #54 , we should capture the scan, read, and returned magnification as fields in this dict. Currently I use 'factor' for this purpose but this name is vague.
